site_name: Tech Learning

theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  
  - pymdownx.keys


# Page tree
nav:
  - Home: 
    - CICD 路線圖: index.md
    - Networking Basics:
      - 無類別區隔路由 CIDR: networking/cidr/cidr-intro.md
    - YAML:
      - YAML 入門教程: yaml/yaml-intro.md
      - Learn YAML: yaml/yaml-tutorial.md
    - CI/CD:
      - GitOps 的概念: cicd/gitops.md
  - Coding:
    - 12 Factors:
      - 12 要素應用實戰: coding/12factors/architecture-12-factor-app.md
    - Observability:
      - 指標 Metrics:
        - 可觀測性(metrics)實戰: coding/observability/metrics/metrics-app-integration.md
      - 日誌 Logs:
        - Structured Logging: coding/observability/logs/structured-logging.md
        - 可觀測性(logging)實戰: coding/observability/logs/logging-app-integration.md
    - C#: 
      - 後端 API:
        - 使用 NET Core 創建 Web API: coding/dotnet/backend/base/web-api-base.md
        - 儀器化 Net Core 應用程序: coding/dotnet/backend/metric/web-api-metric.md
        - 結構化日誌 Net Core 應用程序: coding/dotnet/backend/logging/web-api-logging.md
    - Java:
      - 後端 API:
        - 使用 Springboot 創建 Web API: coding/java/backend/base/web-api-base.md
        - 儀器化 Springboot 應用程序: coding/java/backend/metric/web-api-metric.md
        - 結構化日誌 Sprintboot 應用程序: coding/java/backend/logging/web-api-logging.md
  - Kubernetes:
    - Getting started:
      - 學習環境:
        - K3D:
          - 使用 K3D 設置 Kubernetes 集群: kubernetes/01-getting-started/learning-env/k3d/k3s-kubernetes-cluster-setup-with-k3d.md
        - Minikube:
          - 如何在 Ubuntu 20.04 上安裝 Minikube: kubernetes/01-getting-started/learning-env/minikube/how-to-install-minikube-on-ubuntu.md
    - Concepts:
      - 概述:
        - K8S 介詔: kubernetes/02-concepts/01-overview/k8s-intro.md
      - Kubernetes 架構:
        - K8S 架構解析: kubernetes/02-concepts/02-cluster-architecture/k8s-architecture.md
      - Serivce, 負載均衡與網路:
        - K8S 網絡通信介紹: kubernetes/02-concepts/05-svc-lb-network/k8s-network-intro.md
        - 應用程序向外部公開服務手法: kubernetes/02-concepts/05-svc-lb-network/app-service-type.md
        - 在 K3D 設定 Metallb: kubernetes/02-concepts/05-svc-lb-network/k3d-metallb-starter-kit.md
      - 存儲:
        - 簡介: kubernetes/02-concepts/06-storage/index.md
      - 配置:
        - 配置最佳實踐: kubernetes/02-concepts/07-configuration/overview.md
        - ConfigMap: kubernetes/02-concepts/07-configuration/configmap.md
        - Secret: kubernetes/02-concepts/07-configuration/secret.md
      - 集群管理:
        - 日誌架構: kubernetes/02-concepts/11-cluster-adm/logging.md
        - 日誌完整指南: kubernetes/02-concepts/11-cluster-adm/kubernetes-logging.md
    - Tasks:
      - 管理 Kubernetes 對象:
        - 使用 Kustomize 對 Kubernetes 對象進行聲明式管理: kubernetes/03-tasks/manage-kubernetes-objects/kustomization.md
      - 訪問集群中的應用程序:
        - 部署和訪問 Kubernetes 儀表板: kubernetes/03-tasks/access-application-cluster/web-ui-dashboard.md
      - 監控、日誌和除錯:
        - 應用程序故障排查:
          - 簡介: kubernetes/03-tasks/debug/debug-application/index.md
        - 集群故障排查:
          - 簡介: kubernetes/03-tasks/debug/debug-cluster/index.md
    - Autoscale:
      - Kubernetes 自動縮放: kubernetes/autoscale/kubernetes-autoscaling.md
      - Kubernetes 垂直自動縮放: kubernetes/autoscale/kubernetes-vpa.md
    - Tutorials:
      - 你好, K3D: kubernetes/04-tutorials/hello-k3d.md
      - 學習 Kubernetes 基礎知識: 
        - 簡介: kubernetes/04-tutorials/kubernetes-basics/index.md
        - 創建集群: kubernetes/04-tutorials/kubernetes-basics/create-cluster.md
        - 部署應用: kubernetes/04-tutorials/kubernetes-basics/deploy-app.md
        - 了解應用: kubernetes/04-tutorials/kubernetes-basics/explore.md
        - 公開曝露應用: kubernetes/04-tutorials/kubernetes-basics/expose.md
        - 縮放你的應用: kubernetes/04-tutorials/kubernetes-basics/scale.md
        - 更新你的應用: kubernetes/04-tutorials/kubernetes-basics/update.md
      - 配置:
        - ConfigMap 與 Secret: kubernetes/04-tutorials/configuration/configmap-secrets.md
      - 存儲:
        - 存儲管理 volume、PV/PVC: kubernetes/04-tutorials/volume/volume-pv-pvc.md

    - Reference:
      - API 概述:
        - 使用 K8S API: kubernetes/05-reference/using-api/working-with-k8s-api.md
        - K8S API 基礎: kubernetes/05-reference/using-api/kubernetes-api-structure-and-terminology.md
        - 用 HTTP 客戶端調用 K8S API: kubernetes/05-reference/using-api/kubernetes-api-call-simple-http-client.md
      - API 存取權限控制:
        - Kubernetes RBAC 介詔: kubernetes/05-reference/access-authn-authz/rbac-intro.md
        - 使用 RBAC 設置服務帳戶權限: kubernetes/05-reference/access-authn-authz/k8s-authorization-of-sa-with-rbac.md
        - ServiceAccounts、JWT-tokens、身份驗證和 RBAC 授權: kubernetes/05-reference/access-authn-authz/k8s-sa-jwt-rbac.md
    - Observability:
      - Day2 運營:
        - Day2 的定義: kubernetes/observability/day2-ops/day2-definition.md
        - Day2 的挑戰: kubernetes/observability/day2-ops/day2-challenges.md
        - Kubernetes Day2 運營: kubernetes/observability/day2-ops/k8s-day2-problem.md
      - 概念:
        - Kubernetes 可觀察性: kubernetes/observability/concept/fullstack-monitoring.md
        - 監控 Kubernetes 的挑戰: kubernetes/observability/concept/kubernetes-observability-for-humans.md
      - Observability 學習指南:
        - Part 1. 學習指南說明: kubernetes/observability/concept/observability-prometheus-guide-part1.md
        - Part 2. Prometheus, Alertmanager & Grafana 架構介詔: kubernetes/observability/concept/observability-prometheus-guide-part2.md
        - Part 3. Prometheus & Alertmanager 基本概念: kubernetes/observability/concept/observability-prometheus-guide-part3.md
        - Part 4. PromQL 介詔: kubernetes/observability/concept/observability-prometheus-guide-part4.md
        - Part 5. Alerts 最佳實踐: kubernetes/observability/concept/observability-prometheus-guide-part5.md
        - Part 6. Kubernetes 中安裝設定 Prometheus 指南: kubernetes/observability/concept/observability-prometheus-guide-part6.md
      - 日誌 Logging:
        - Loki:
          - 使用 Loki 做為 Kubernetes 的日誌聚合亓件: kubernetes/observability/logging/loki/logging-with-loki-and-plg.md
          - 使用 Logging Operator 將 Nginx 日誌存儲在 Grafana Loki: kubernetes/observability/logging/loki/loki-nginx.md
          - Loki 查詢語言 LogQL: kubernetes/observability/logging/loki/loki-ql.md
        - Logging Operator:
          - Logging Operator 日誌管理方案: kubernetes/observability/logging/operator/logging-operator.md
          - Logging Operator 的擴展: kubernetes/observability/logging/operator/logging-operator-extensions.md
          - Rancher 2.6 全新 Logging 快速入門: kubernetes/observability/logging/operator/rancher-logging-quickstart-01.md
          - Rancher 2.6 全新 Logging 快速入門(2): kubernetes/observability/logging/operator/rancher-logging-quickstart-02.md
      - 指標 Metrics:
        - Prometheus Operator:
          - Prometheus-operator 介绍和配置解析: kubernetes/observability/metrics/kube-prometheus-stack/setup-prometheus-and-grafana-on-kubernetes.md
      - 追踪 Traces:
        - 開發語言:
          - Java:
            - SpringBoot: kubernetes/observability/tracing/java/spring-boot-opentelemetry.md
          - Dotnet:
            - 可觀測性(Observability): kubernetes/observability/tracing/dotnet/modern-monitoring-using-openTelemetry-with-Observability.md
    - Tools:
      - 簡介: kubernetes/package/index.md
      - Packaging 管理:
          - Helm:
            - Helm 入門教學: kubernetes/package/helm-intro.md
            - K8S 應用部署之 Helm 初探: kubernetes/package/helm-app-deploy.md
      - Config 管理:
          - Kustomize:
            - Kustomize 入門教學: kubernetes/package/helm-intro.md  
  - Prometheus:
    - 基礎:
      - Prometheus 簡介: prometheus/prometheus/overview.md
      - Prometheus 安裝配置: prometheus/prometheus/install.md
    - Node Exporter:
      - Exporter 簡介: prometheus/node-exporter/overview.md
      - 安裝配置: prometheus/node-exporter/install.md
      - 常用監控指標: prometheus/node-exporter/metrics.md
    - PromQL:
      - 基礎:
        - PromQL 簡介: prometheus/promql/intro.md
        - 數據模型: prometheus/promql/data-model.md
        - 指標類型: prometheus/promql/metric-type.md
        - 演示服務: prometheus/promql/demo-service.md
      - 查詢:
        - 查詢基礎: prometheus/promql/theory.md
        - 選擇時間序列: prometheus/promql/select-series.md
        - 變化率: prometheus/promql/rates.md
        - 聚合: prometheus/promql/aggregate.md
        - 運算: prometheus/promql/operate.md
        - 閾值: prometheus/promql/threshold.md
        - 集合操作: prometheus/promql/set.md
        - 排序: prometheus/promql/sort.md
        - 直方圖: prometheus/promql/histograms.md
        - 數據對比: prometheus/promql/compare.md
        - 檢測: prometheus/promql/check.md
      - 補充:
          - Range query 的 step 參數說明: prometheus/promql/range-query-step.md
          - 搞懂 Prometheus 的直方圖: prometheus/promql/metric-histogram.md
          - 簡單理解 Summary 和 Histogram 指標: prometheus/promql/metric-histogram-summary.md
    - Alertmanager:
      - Alertmanager 安裝: prometheus/alertmanager/deploy.md
      - 報警規則: prometheus/alertmanager/rules.md
      - 報警接收器: prometheus/alertmanager/receiver.md
      - 報警過濾: prometheus/alertmanager/filter.md
      - 補充:
          - Promtheus 到底啥時候報警?: prometheus/alertmanager/prometheus-alert-why.md
    - Grafana:
      - Grafana 簡介: prometheus/grafana/overview.md
      - 視覺化面板:
        - 面板介詔: prometheus/grafana/panel.md
        - 圖形面板: prometheus/grafana/graph.md
        - 圖形定制: prometheus/grafana/graph-custom.md
        - 表格面板: prometheus/grafana/table.md
        - 儀錶盤面板: prometheus/grafana/gauge.md
        - 統計面板: prometheus/grafana/stat.md
        - 文本面板: prometheus/grafana/text.md      
    - Prometheus Operator:
      - Prometheus Operator 簡介: prometheus/operator/install.md
      - 自定義監控報警: prometheus/operator/custom.md
      - Dashboard 的 GitOps 方式: prometheus/operator/consistent-dashboard-gitops-way.md
      - 使用 ConfigMap 管理 Grafana 儀表板: prometheus/operator/dashboard-using-configmap.md
    - Operation Runbook:
      - Operation Runbook 簡介: prometheus/runbook/operations-runbook.md
    - PostgresExporter:
      - 使用 Prometheus 監控 PostgreSQL: prometheus/postgres-exporter/postgres-exporter-integration.md
  - OpenTelemetry:
    - Instrumentation:
      - 簡介: opentelemetry/instrumentation/index.md
      - Java:
        - 簡介: opentelemetry/instrumentation/java/index.md
        - Automatic:
          - 簡介: opentelemetry/instrumentation/java/automatic/index.md
    - Collector:
      - 簡介: opentelemetry/collector/index.md
    - K8s Operator:
      - 簡介: opentelemetry/k8s-operator/index.md
    - 範例:
      - 如何使用 OTEL agent 捕獲 Spring Boot 指標: opentelemetry/sample/java/springboot-otel-agent.md
  - Grafana:
    - Tempo:
      - 示例:
        - Hot ROD 應用: grafana/tempo/hotrod.md
  - ArgoCD:
    - ArgoCD 教程:
      - ArgoCD 教程簡介: argocd/tutorial/index.md
      - ArgoCD 安裝設定: argocd/tutorial/01-setup.md
      - ArgoCD 入門: argocd/tutorial/02-getting_started.md
      - Kustomize: argocd/tutorial/03-kustomize.md
      - SyncWaves 與 Hooks: argocd/tutorial/04-syncwaves-hooks.md
      - ApplicationSet 控制器: argocd/tutorial/argo-cd-applicationset-controller.md
    - ArgoCD 插件:
      - 使用 Argo CD Vault 插件進行 Secret 管理: argocd/argocd-vault-plugin/secret-management-argocd-vault.md
    - ApplicationSet Controller:
      - 簡介: argocd/applicationset/intro.md
      - 用例: argocd/applicationset/use-cases.md
      - ApplicationSet 控制器與 Argo CD 整合: argocd/applicationset/argo-cd-integration.md
      - Generator 生成器:
        - 生成器簡介: argocd/applicationset/generators/index.md
        - List Generator: argocd/applicationset/generators/generators-list.md
        - Cluster Generator: argocd/applicationset/generators/generators-cluster.md
        - Git Generator: argocd/applicationset/generators/generators-git.md
      - 範本 fields: argocd/applicationset/template.md
  - Istio:
    - 概念:
      - Istio 是什麼？: istio/concepts/what-is-istio.md
      - 流量管理: istio/concepts/traffic-management.md
      - 可觀測性: istio/concepts/observability.md
      - 安全: istio/concepts/security.md
    - 簡介: istio/index.md
    - 安裝: 
      - 使用 Helm 安裝: istio/setup/install/helm/helm-install.md
      - 更多指南:
        - 安裝配置文件: istio/setup/additional-setup/config-profiles.md
    - 示例:
      - Bookinfo 應用: istio/examples/bookinfo.md
    - 參考:
      - 應用程序部署策略: istio/reference/deployment-strategies.md
      - Istio Ingress 與 K8S Ingress: istio/reference/istio-ingress-vs-k8s-ingress.md
      
  - Vault:
    - Docs:
      - Auth Methods:
        - Overview: vault/docs/auth/overview.md
        - Kubernetes: vault/docs/auth/kubernetes.md
        - Username & Password: vault/docs/auth/userpass.md
      - Platform:
        - Kubernetes:
          - Overview: vault/docs/platform/index.md
          - Helm:
            - Overview: vault/docs/platform/helm/index.md
    - Tutorials:        
      - Kubernetes:
        - 通過 Vault Agent 容器將 Secret 注入 Kubernetes Pod: vault/kubernetes/kubernetes-sidecar.md
        - 通過容器存儲接口 (CSI) 掛載 Vault Secret: vault/kubernetes/kubernetes-secret-store-driver.md
        - Vault Agent 與 Kubernetes: vault/kubernetes/agent-kubernetes.md
        - Kubernetes 與外部 Vault 整合: vault/kubernetes/kubernetes-external-vault.md
  - Ansible:
    - 快速入門:
      - Vagrant 快速入門: ansible/vagrant-intro.md
      - Ansible 快速入門: ansible/ansible-intro.md
      - Ansible 使用基於 SSH 密碼登入: ansible/use_sshpass_to_login_for_ansible.md
      - Ansible 使用指南: ansible/ansible-cheatsheet.md
    - Ansible Playbook 撰寫:
      - 如何創建與運行: ansible/tutorial_playbook/creating-and-running-your-first-ansible-playbook.md
      - 如何定義任務: ansible/tutorial_playbook/how-to-define-tasks-in-ansible-playbooks.md
      - 如何使用變量: ansible/tutorial_playbook/how-to-use-variables-in-ansible-playbooks.md
      - 如何訪問系統信息: ansible/tutorial_playbook/how-to-access-system-information-facts-in-ansible-playbooks.md
      - 如何使用條件: ansible/tutorial_playbook/how-to-use-conditionals-in-ansible-playbooks.md
      - 如何使用循環: ansible/tutorial_playbook/how-to-use-loops-in-ansible-playbooks.md
      - 了解權限提升: ansible/tutorial_playbook/understanding-privilege-escalation-in-ansible-playbooks.md
      - 如何安裝和管理系統包: ansible/tutorial_playbook/how-to-install-and-manage-system-packages-in-ansible-playbooks.md
      - 如何創建和使用模板: ansible/tutorial_playbook/how-to-create-and-use-templates-in-ansible-playbooks.md
      - 如何定義和使用處理程序: ansible/tutorial_playbook/how-to-define-and-use-handlers-in-ansible-playbooks.md
      - 如何使用Nginx部署靜態HTML網站: ansible/tutorial_playbook/how-to-deploy-a-static-html-website-with-ansible-on-ubuntu-20-04-nginx.md
    - Ansible AWX 教學:
      - 如何在 Ubuntu 20.04 上安裝 Ansible AWX: ansible/tutorial_awx/how-to-install-ansible-awx.md
      - Ansible AWX 基本使用和配置: ansible/tutorial_awx/ansible-awx-guide-basic-usage-and-configuration.md
    - 教學:
      - 如何在 Ubuntu 20.04 上安裝 Docker: ansible/tutorial/ubuntu-insall-docker.md
      - 如何使用 Ansible 在 Ubuntu 20.04 上安裝和設置 Docker: ansible/tutorial/ansible-install-docker.md
      - 如何在 Ubuntu 22.04 上安裝和配置 Ansible: ansible/tutorial/how-to-install-and-configure-ansible-on-ubuntu-22-04.md


