site_name: Tech Learning

theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  
  - pymdownx.keys


# Page tree
nav:
  - Home: 
    - CICD 路線圖: index.md
    - Networking Basics:
      - 無類別區隔路由 CIDR: networking/cidr/cidr-intro.md
    - YAML:
      - YAML 入門教程: yaml/yaml-intro.md
      - Learn YAML: yaml/yaml-tutorial.md
    - CI/CD:
      - GitOps 的概念: cicd/gitops.md
  - Kubernetes:
    - Getting started:
      - 學習環境:
        - K3D:
          - 使用 K3D 設置 Kubernetes 集群: kubernetes/01-getting-started/learning-env/k3d/k3s-kubernetes-cluster-setup-with-k3d.md
        - Minikube:
          - 如何在 Ubuntu 20.04 上安裝 Minikube: kubernetes/01-getting-started/learning-env/minikube/how-to-install-minikube-on-ubuntu.md
    - Concepts:
      - 概述:
        - K8S 介詔: kubernetes/02-concepts/01-overview/k8s-intro.md
      - Kubernetes 架構:
        - K8S 架構解析: kubernetes/02-concepts/02-cluster-architecture/k8s-architecture.md
      - Serivce, 負載均衡與網路:
        - K8S 網絡通信介紹: kubernetes/02-concepts/05-svc-lb-network/k8s-network-intro.md
      - 存儲:
        - 簡介: kubernetes/02-concepts/06-storage/index.md
      - 配置:
        - 配置最佳實踐: kubernetes/02-concepts/07-configuration/overview.md
        - ConfigMap: kubernetes/02-concepts/07-configuration/configmap.md
        - Secret: kubernetes/02-concepts/07-configuration/secret.md
      - 集群管理:
        - 日誌架構: kubernetes/02-concepts/11-cluster-adm/logging.md
        - 日誌完整指南: kubernetes/02-concepts/11-cluster-adm/kubernetes-logging.md

    - Tasks:
      - 管理 Kubernetes 对象:
        - 使用 Kustomize 對 Kubernetes 對象進行聲明式管理: kubernetes/03-tasks/manage-kubernetes-objects/kustomization.md
      - 監控、日誌和除錯:
        - 應用程序故障排查:
          - 簡介: kubernetes/03-tasks/debug/debug-application/index.md
        - 集群故障排查:
          - 簡介: kubernetes/03-tasks/debug/debug-cluster/index.md

    - Tutorials:
      - 你好, K3D: kubernetes/04-tutorials/hello-k3d.md
      - 學習 Kubernetes 基礎知識: 
        - 簡介: kubernetes/04-tutorials/kubernetes-basics/index.md
        - 創建集群: kubernetes/04-tutorials/kubernetes-basics/create-cluster.md
        - 部署應用: kubernetes/04-tutorials/kubernetes-basics/deploy-app.md
        - 了解應用: kubernetes/04-tutorials/kubernetes-basics/explore.md
        - 公開曝露應用: kubernetes/04-tutorials/kubernetes-basics/expose.md
        - 縮放你的應用: kubernetes/04-tutorials/kubernetes-basics/scale.md
        - 更新你的應用: kubernetes/04-tutorials/kubernetes-basics/update.md
      - 配置:
        - ConfigMap 與 Secret: kubernetes/04-tutorials/configuration/configmap-secrets.md
      - 存儲:
        - 存儲管理 volume、PV/PVC: kubernetes/04-tutorials/volume/volume-pv-pvc.md

    - Reference:
      - API 概述:
        - 使用 K8S API: kubernetes/05-reference/using-api/working-with-k8s-api.md
        - K8S API 基礎: kubernetes/05-reference/using-api/kubernetes-api-structure-and-terminology.md
        - 用 HTTP 客戶端調用 K8S API: kubernetes/05-reference/using-api/kubernetes-api-call-simple-http-client.md
      - API 存取權限控制:
        - Kubernetes RBAC 介詔: kubernetes/05-reference/access-authn-authz/rbac-intro.md
        - 使用 RBAC 設置服務帳戶權限: kubernetes/05-reference/access-authn-authz/k8s-authorization-of-sa-with-rbac.md
        - ServiceAccounts、JWT-tokens、身份驗證和 RBAC 授權: kubernetes/05-reference/access-authn-authz/k8s-sa-jwt-rbac.md
    - Observability:
      - 概念:
        - Kubernetes 可觀察性: kubernetes/observability/concept/fullstack-monitoring.md
        - 監控 Kubernetes 的挑戰: kubernetes/observability/concept/kubernetes-observability-for-humans.md
      - 日誌 Logging:
        - Loki:
          - 使用 Loki 做為 Kubernetes 的日誌聚合亓件: kubernetes/observability/logging/loki/logging-with-loki-and-plg.md
          - 使用 Logging Operator 將 Nginx 日誌存儲在 Grafana Loki: kubernetes/observability/logging/loki/loki-nginx.md
        - Operator:
          - Logging Operator 日誌管理方案: kubernetes/observability/logging/operator/logging-operator.md
      - 指標 Metrics:
        - Prometheus:
          - Prometheus-operator 介绍和配置解析: kubernetes/observability/metrics/kube-prometheus-stack/setup-prometheus-and-grafana-on-kubernetes.md
    - Tools:
      - 簡介: kubernetes/package/index.md
      - Packaging 管理:
          - Helm:
            - Helm 入門教學: kubernetes/package/helm-intro.md
            - K8S 應用部署之 Helm 初探: kubernetes/package/helm-app-deploy.md
      - Config 管理:
          - Kustomize:
            - Kustomize 入門教學: kubernetes/package/helm-intro.md
  - ArgoCD:
    - ArgoCD 教程:
      - ArgoCD 教程簡介: argocd/tutorial/index.md
      - ArgoCD 安裝設定: argocd/tutorial/01-setup.md
      - ArgoCD 入門: argocd/tutorial/02-getting_started.md
      - Kustomize: argocd/tutorial/03-kustomize.md
      - SyncWaves 與 Hooks: argocd/tutorial/04-syncwaves-hooks.md
      - ApplicationSet 控制器: argocd/tutorial/argo-cd-applicationset-controller.md
    - ArgoCD 插件:
      - 使用 Argo CD Vault 插件進行 Secret 管理: argocd/argocd-vault-plugin/secret-management-argocd-vault.md
    - ApplicationSet Controller:
      - 簡介: argocd/applicationset/intro.md
      - 用例: argocd/applicationset/use-cases.md
      - ApplicationSet 控制器與 Argo CD 整合: argocd/applicationset/argo-cd-integration.md
      - Generator 生成器:
        - 生成器簡介: argocd/applicationset/generators/index.md
        - List Generator: argocd/applicationset/generators/generators-list.md
        - Cluster Generator: argocd/applicationset/generators/generators-cluster.md
        - Git Generator: argocd/applicationset/generators/generators-git.md
      - 範本 fields: argocd/applicationset/template.md
  - Vault:
    - Docs:
      - Auth Methods:
        - Overview: vault/docs/auth/overview.md
        - Kubernetes: vault/docs/auth/kubernetes.md
        - Username & Password: vault/docs/auth/userpass.md
      - Platform:
        - Kubernetes:
          - Overview: vault/docs/platform/index.md
          - Helm:
            - Overview: vault/docs/platform/helm/index.md
    - Tutorials:        
      - Kubernetes:
        - 通過 Vault Agent 容器將 Secret 注入 Kubernetes Pod: vault/kubernetes/kubernetes-sidecar.md
        - 通過容器存儲接口 (CSI) 掛載 Vault Secret: vault/kubernetes/kubernetes-secret-store-driver.md
        - Vault Agent 與 Kubernetes: vault/kubernetes/agent-kubernetes.md
        - Kubernetes 與外部 Vault 整合: vault/kubernetes/kubernetes-external-vault.md
  - Ansible:
    - 快速入門:
      - Vagrant 快速入門: ansible/vagrant-intro.md
      - Ansible 快速入門: ansible/ansible-intro.md
      - Ansible 使用基於 SSH 密碼登入: ansible/use_sshpass_to_login_for_ansible.md
      - Ansible 使用指南: ansible/ansible-cheatsheet.md
    - Ansible Playbook 撰寫:
      - 如何創建與運行: ansible/tutorial_playbook/creating-and-running-your-first-ansible-playbook.md
      - 如何定義任務: ansible/tutorial_playbook/how-to-define-tasks-in-ansible-playbooks.md
      - 如何使用變量: ansible/tutorial_playbook/how-to-use-variables-in-ansible-playbooks.md
      - 如何訪問系統信息: ansible/tutorial_playbook/how-to-access-system-information-facts-in-ansible-playbooks.md
      - 如何使用條件: ansible/tutorial_playbook/how-to-use-conditionals-in-ansible-playbooks.md
      - 如何使用循環: ansible/tutorial_playbook/how-to-use-loops-in-ansible-playbooks.md
      - 了解權限提升: ansible/tutorial_playbook/understanding-privilege-escalation-in-ansible-playbooks.md
      - 如何安裝和管理系統包: ansible/tutorial_playbook/how-to-install-and-manage-system-packages-in-ansible-playbooks.md
      - 如何創建和使用模板: ansible/tutorial_playbook/how-to-create-and-use-templates-in-ansible-playbooks.md
      - 如何定義和使用處理程序: ansible/tutorial_playbook/how-to-define-and-use-handlers-in-ansible-playbooks.md
      - 如何使用Nginx部署靜態HTML網站: ansible/tutorial_playbook/how-to-deploy-a-static-html-website-with-ansible-on-ubuntu-20-04-nginx.md
    - Ansible AWX 教學:
      - 如何在 Ubuntu 20.04 上安裝 Ansible AWX: ansible/tutorial_awx/how-to-install-ansible-awx.md
      - Ansible AWX 基本使用和配置: ansible/tutorial_awx/ansible-awx-guide-basic-usage-and-configuration.md
    - 教學:
      - 如何在 Ubuntu 20.04 上安裝 Docker: ansible/tutorial/ubuntu-insall-docker.md
      - 如何使用 Ansible 在 Ubuntu 20.04 上安裝和設置 Docker: ansible/tutorial/ansible-install-docker.md
      - 如何在 Ubuntu 22.04 上安裝和配置 Ansible: ansible/tutorial/how-to-install-and-configure-ansible-on-ubuntu-22-04.md


